### ISSUE TITLE
pass方法的管道操作

### ISSUE THREAD

**Issue by fbbin** [zheng-ji/goTcpProxy#3]
不应该在select的default中添加一行：
`oneSide <- true`
么？

**Comment by zheng-ji** [comment]
应该是不需要的。

pass 逻辑中建立双向连接，如果一端连接出错就会

```
complete <- true
oneSide <- true
```

这使得另一个 pass goroutine 执行

```
case <- otherSide:
    complete <- true
```

如果两端连接都保持健康，数据就持续保持在双端传送。不会退出循环。

假如按照你说的，在 default 分支 里面写入

```
oneSide<-true
```

一次 go pass 就使得另一个对端传输退出循环了。数据就不能正常传输.
你可以试验一下。

**Comment by fbbin** [comment]
嗯，你说的对的，我后来试了几次，确实如此，谢谢你，是我一开始理解错了。
